name: Check Markdown

on: [pull_request]

jobs:
  check-blog-markdown:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@main
  
    - name: Install markdownlint
      run: sudo npm install -g markdownlint-cli

    - name: Check markdown
      run: markdownlint -c .ci/markdown_config.json $(git diff --name-only main...HEAD | grep -e "md$")

    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        check-modified-files-only: 'yes'
        base-branch: 'main'
