name: Update Blog

on:
  push:
    branches:
      - main

jobs:
  update_blog:
    runs-on: ubuntu-latest
    if: github.repository == 'emqx/blog' && github.event.head_commit.author.email != 'ci@emqx.io'
    steps:
      - name: Check out code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v8.3.2
        with:
          enable-cache: false

      - name: Update blogs
        env:
          UPDATE_API: ${{ secrets.UPDATE_API }}
          UPDATE_TOKEN: ${{ secrets.UPDATE_TOKEN }}
        run: |
          if git diff HEAD^ HEAD --name-only | grep -e "md$"; then
            changed_files=$(git diff HEAD^ HEAD --name-only | grep -e "md$")
            uv run .ci/update_blog.py $(pwd) $changed_files
          fi
